Adding project improvements in integration tests

diff --git a/functions/city-read-function/tools/shell/java/bootstrap b/functions/city-read-function/tools/shell/java/bootstrap
--- a/functions/city-read-function/tools/shell/java/bootstrap
+++ b/functions/city-read-function/tools/shell/java/bootstrap
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+cd "${LAMBDA_TASK_ROOT:-.}" || {
+    echo "cd command failed. Exiting."; exit 1;
+}
+
 java -agentlib:native-image-agent=config-output-dir="$AGENT_OUTPUT_DIR"  \
      -cp .:"$(echo lib/*.jar | tr ' ' :)"                                \
      "$MAIN_CLASS"
